### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by khornberg** [rmmmp/ember-daux#8]
I like this idea. I would really like to see the internals of ember data changed to an immutable object but understand that is large undertaking, and thus this project follows that idea and is probably more likely to accomplish that any time soon.

I have several questions.

```
export default class User extends Model {
  static get attributes() {
    return ['name'];
  }
```
What is `static`? Is that a new syntax in a Javascript class?

Are there plans for adapters and serializers?
Why normalize a record in the model?

Is a model curator required? Why have one?

In my route, why do I have to `this.store.subscribe(() => this.refresh());`?

In the model, do I need to declare the fields or is that automatically handled by the normalized record function?

Does this impose or prefer any api request/response structure such as JSON-API?

**Comment by khornberg** [comment]
And does this relate to ember-redux in form or fashion?

**Comment by rmmmp** [comment]
First of all, this library is still in its early stages. The APIs can change rapidly. I don't recommend using this yet in your projects (yet). Right now, I'm using this in a personal project so I can flesh out the general feature of this library.

**What is `static`?**

It's part of the ES6 `class` spec. You can read more about it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static).

**Are there plans for adapters and serializers?**

I'd like to avoid those as much as possible. IMO, they're one of the reason why Ember Data is so hard to adopt.

**Why normalize a record in the model?**

The model is just a blueprint. It's not been instantiated or whatsoever. When you do `this.store.get('user', 'user_id')`, you get plain immutable object, not an instance of `User` model.

Basically, its sole responsibility is to indicate how a model would look like. I think the `normalize` function is fit to be inside this *blueprint*.

**Is a model curator required?**

I'm planning to separate Daux as a standalone library and then `ember-daux` being just a seamless integration to Ember just like how `react-redux` and `redux` works.

For Daux as a standalone library to find out what the model for `user` in `store.get('user', 'user_id')` is, is for the model to be fed into the `store`. You could imagine it being like this:

```javascript
import { Store } from 'daux';
import User from './models/user';
import Post from './models/post';

const store = new Store({
  user: User,
  post: Post
});
````

Now with the model curator, the above code can be done by `ember-daux` for you from behind the scenes. This is **one** of the seamless integrations to Ember that I've mentioned above.

**Why do I have to `this.store.subscribe(() => this.refresh());`?**

This is one of the patterns that I've taken from Redux. Since data is immutable, making a change to a record state won't cause the components to re-render. `Store.subscribe()` fixes this, and the `Route.refresh()` on the routes is just one of the ways to re-render the view when a state changes.

**In the model, do I need to declare the fields or is that automatically handled by the normalized record function?**

You need to declare the fields and relationship. If your API response returns something like this:

```json
{
  "id": "user_a",
  "name": "Foo Bar",
  "age": 25
}
```

And your model has `['name']` only for the `attributes`, the `age` property from your response would be dropped.

**Does this impose or prefer any api request/response structure such as JSON-API?**

No this doesn't. Feel free to use any response structure that you like. Just use the `normalize` hook to reformat it to match your models.

**And does this relate to ember-redux in form or fashion?**

It's only related to [Redux](https://redux.js.org/) in some principles. Nothing about `redux` or `ember-redux` is being used internally in this library.

**Comment by khornberg** [comment]
Thank you that helps
